/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jdbc;

import java.sql.SQLException;

public class App {

    public static void main(String[] args) throws ClassNotFoundException, SQLException {
        Database.database();
    }
    
}
